input_dir: /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/det_var/wiremod
#output_dir: /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/det_var/wiremod
output_dir: /pnfs/sbnd/persistent/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/det_var/wiremod

jobs:
  - name: nosyst_nocuts_recomb
    enabled: true
    description: INCLUDE_WEIGHTS=False, SLIM=False, UPDATE_RECOMB=False
    base_config: analysis_village.numuincl.configs.base
    dfs:
      - makedf.makedf.make_hdrdf
      - makedf.makedf.make_mcnudf
      - analysis_village.numuincl.makedf1muX.make_pandora_evtdf_processed
      - analysis_village.numuincl.makedf1muX.make_custom_trkdf
    names: [hdr, mcnu, evt_pand, trk]
    input_list: wiremodyz.list
    output: mc_wiremodyz_nosyst_nocuts_recomb_med
    settings:
      INCLUDE_WEIGHTS: false
      SLIM: false
      UPDATE_RECOMB: false
      VERBOSE: false
    args:
      ngrid: 0
      ncpu: 50
      nfile: 10000