input_dir: /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/mc_lowe/v4
output_dir: /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/mc_lowe/v5
#output_dir: /pnfs/sbnd/persistent/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/pandora/mc_lowe/v5

jobs:
  # - name: nosyst_nocuts_recomb
  #   enabled: true
  #   description: INCLUDE_WEIGHTS=False, SLIM=False, UPDATE_RECOMB=True, ADD_STAT_UNC=False
  #   base_config: analysis_village.numuincl.configs.base
  #   dfs:
  #     - makedf.makedf.make_hdrdf
  #     - makedf.makedf.make_mcnudf
  #     - analysis_village.numuincl.makedf1muX.make_pandora_evtdf_processed
  #     - analysis_village.numuincl.makedf1muX.make_custom_trkdf
  #   names: [hdr, mcnu, evt_pand, trk]
  #   input_list: mc_fullpand.list
  #   output: mc_medpand_nosyst_nocuts_recomb3
  #   settings:
  #     INCLUDE_WEIGHTS: false
  #     SLIM: false
  #     UPDATE_RECOMB: true
  #     VERBOSE: false
  #     ADD_STAT_UNC: false
  #   args:
  #     ngrid: 0
  #     ncpu: -1
  #     nfile: 10000

  - name: fullsyst_fullcuts_norecomb
    enabled: true
    description: INCLUDE_WEIGHTS=False, SLIM=False, UPDATE_RECOMB=False, FULL_CUTS=True, ADD_STAT_UNC=False
    base_config: analysis_village.numuincl.configs.base
    dfs:
      - makedf.makedf.make_hdrdf
      - makedf.makedf.make_mcnudf
      - analysis_village.numuincl.makedf1muX.make_pandora_evtdf_processed_signal_cut
      - analysis_village.numuincl.makedf1muX.make_pandora_evtdf_processed_selected_cut
    names: [hdr, mcnu, evt_pand_signal, evt_pand_selected]
    input_list: mc_fullpand.list
    output: mc_medpand_fullsyst_cut_norecomb4
    settings:
      INCLUDE_WEIGHTS: true
      SLIM: false
      UPDATE_RECOMB: false
      VERBOSE: false
      ADD_STAT_UNC: false
    args:
      ngrid: 0
      ncpu: 30
      nfile: 1000

  - name: slimsyst_nocuts_norecomb
    enabled: true
    description: INCLUDE_WEIGHTS=True, SLIM=True, UPDATE_RECOMB=False, ADD_STAT_UNC=True
    base_config: analysis_village.numuincl.configs.base
    dfs:
      - makedf.makedf.make_hdrdf
      - makedf.makedf.make_mcnudf
      - analysis_village.numuincl.makedf1muX.make_pandora_evtdf_processed
    names: [hdr, mcnu, evt_pand]
    input_list: mc_fullpand.list
    output: mc_smallpand_slimsyst_nocuts_norecomb4
    settings:
      INCLUDE_WEIGHTS: true
      SLIM: true
      UPDATE_RECOMB: false
      VERBOSE: false
      ADD_STAT_UNC: true
    args:
      ngrid: 0
      ncpu: 30
      nfile: 1000