#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/cv/mc_full_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/cv/full.list
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTGainFluct/mc_full_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTGainFluct/full.list # -ngrid 100
python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTHighNoise/mc_full_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTHighNoise/full.list # -ngrid 100
python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTLowEff/mc_full_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTLowEff/full.list # -ngrid 100

#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/cv/mc_small_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/cv/small.list
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTGainFluct/mc_small_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTGainFluct/small.list
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTHighNoise/mc_small_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTHighNoise/small.list
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTLowEff/mc_small_2 -i /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTLowEff/small.list
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/cv/mc_small_2 -i /pnfs/sbn/data_add/sbn_nd/aurora/mc/v10_06_00_04/pds_detsys/prodgenie_corsika_proton_rockbox_sbnd/cv/caf/000000/000000/*.flat.caf.root
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTGainFluct/mc_small_2 -i /pnfs/sbn/data_add/sbn_nd/aurora/mc/v10_06_00_04/pds_detsys/prodgenie_corsika_proton_rockbox_sbnd/PMTGainFluct/caf/000000/000000/*.flat.caf.root
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTHighNoise/mc_small_2 -i /pnfs/sbn/data_add/sbn_nd/aurora/mc/v10_06_00_04/pds_detsys/prodgenie_corsika_proton_rockbox_sbnd/PMTHighNoise/caf/000000/000000/*.flat.caf.root
#python run_df_maker.py -c /exp/sbnd/app/users/brindenc/develop/cafpyana/analysis_village/numuincl/config_nospine.py -o /exp/sbnd/data/users/brindenc/analyze_sbnd/numu/v10_06_00_validation/both/pds_var/PMTLowEff/mc_small_2 -i /pnfs/sbn/data_add/sbn_nd/aurora/mc/v10_06_00_04/pds_detsys/prodgenie_corsika_proton_rockbox_sbnd/PMTLowEff/caf/000000/000000/*.flat.caf.root
